# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/paas.cncp.nl_postgresclusters.yaml
- bases/paas.cncp.nl_valkeyclusters.yaml
- bases/paas.cncp.nl_grafanainstances.yaml
- bases/paas.cncp.nl_mariadbclusters.yaml
- bases/paas.cncp.nl_rabbitmqclusters.yaml
- bases/paas.cncp.nl_prometheusinstances.yaml
- bases/paas.cncp.nl_mongodbclusters.yaml
- bases/paas.cncp.nl_kafkaclusters.yaml
- bases/paas.cncp.nl_lokiinstances.yaml
- bases/paas.cncp.nl_alloyinstances.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
